<div class="row">
    <div class="col-md-6 col-md-offset-3" style="background: #fff; margin-top: 100px; padding-bottom: 20px">
        <a id="logo" href="<?php echo BASE; ?>">
            <img class="img-responsive" src="<?php echo IMG; ?>painel_logo.png" alt="">
        </a> <br>
        <?php echo (isset($this->menu) ? $this->menu : ''); ?>
        <br>
        <div class="alert alert-block alert-danger">
            <h2 style="text-align: center;">Ops! Nada encontrado!<br><small>
            Desculpe-nos, mas a url solicitada não foi encontrada, cheque novamente, caso esteja correta, avise o administrador do <strong>Sistema da Megavale Soluções.</strong></small></h2>
        </div>
    </div>    
</div>



