<div class="row">
    <div class="col-md-4 col-md-offset-4" style="background: #fff; margin-top: 50px; padding-bottom: 20px">
        <div class="row">
            <div class="col-md-12" style="padding-top: 15px">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>painel_logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form action="<?php echo BASE; ?>cadastro/cadastrar/" method="post" >

                  <div class="form-group">
                    <label for="inputname" style="font-size: 18px; color: #666">Nome Completo:</label>
                    <input type="text" name="name" class="form-control input-lg" id="inputname" placeholder="Nome Completo">
                  </div>
                  <div class="form-group">
                    <label for="inputname" style="font-size: 18px; color: #666">E-mail:</label>
                    <input type="text" name="email" class="form-control input-lg" id="inputname" placeholder="Informe seu E-mail Corretamente">
                  </div>
                  <div class="form-group">
                    <label for="inputname" style="font-size: 18px; color: #666">Nome de Usuário:</label>
                    <input type="text" name="username" class="form-control input-lg" id="inputname" placeholder="Informe seu Nome de Usuário">
                  </div>                  
                  <div class="form-group">
                    <label for="inputpass" style="font-size: 18px; color: #666">Sua Senha:</label>
                    <input type="password" name="password" class="form-control input-lg" id="inputpass" placeholder="Password">
                  </div>

                  <button type="submit" class="btn btn-success btn-block btn-lg">Cadastrar no Sistema</button>

                </form>
            </div>
        </div>
    </div>    
</div>

