<div class="row">
    <div class="col-md-4 col-md-offset-4" style="background: #fff; margin-top: 50px; padding-bottom: 20px">
        <div class="row">
            <div class="col-md-12" style="padding-top: 15px">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>painel_logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form action="" method="post" >

                  <div class="alert alert-block alert-info">
                    <h4>Recupere sua Senha.</h4>
                    Um Link de redefinição será enviado para seu e-mail. Por favor verifique sua caixa de SPAM.
                  </div>

                  <div class="form-group">
                    <label for="inputname" style="font-size: 18px; color: #666">Nome de Usuário:</label>
                    <input type="email" name="username" class="form-control input-lg" id="inputname" placeholder="Informe seu Nome de Usuário">
                  </div>

                  <button type="submit" class="btn btn-success btn-block btn-lg">Enviar link de Redefinição</button>

                </form>
            </div>
        </div>
    </div>    
</div>

