<div class="row">
    <div class="col-md-6 col-md-offset-3" style="background: #fff; margin-top: 100px; padding-bottom: 20px">
        <a id="logo" href="<?php echo BASE; ?>">
            <img class="img-responsive" src="<?php echo IMG; ?>painel_logo.png" alt="">
        </a> <br>
        <?php echo (isset($this->menu) ? $this->menu : ''); ?>
        <br>
        <?php
        $this->partial('message', array(
            'msg' => '<p style="text-align:center">Uhull! Você instalou e configurou o Painel da Megavale Soluções com sucesso!</p>'
        ));
        ?>
    </div>    
</div>

